# code: language=ansible
---
- name: Update repositories file
  become: true
  ansible.builtin.replace:
    regexp: v\d+\.\d+
    path: /etc/apk/repositories
    replace: "v{{ alpine_distro_version_desired }}"

- name: Update apk-tools
  become: true
  community.general.apk:
    update_cache: true
    name:
      - apk-tools
    state: latest

- name: Update installed packages
  become: true
  register: alpine_package_upgrade
  community.general.apk:
    update_cache: true
    upgrade: true
    available: true

- name: Sync and reboot # noqa: no-changed-when no-handler
  become: true
  when: alpine_package_upgrade.changed
  ansible.builtin.raw: sync && reboot
  async: 1
  poll: 0

- name: Wait for system to come back online # noqa: no-handler
  when: alpine_package_upgrade.changed
  ansible.builtin.wait_for_connection:
    delay: 15
    timeout: 300
